name: chaguaner2023
description: Chaguaner.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 4.1.0+5

environment:
  sdk: '>=2.14.0 <4.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter
  dio: 5.1.1
  html: ^0.15.4
  html_character_entities: ^1.0.0+1
  html_unescape: ^2.0.0
  go_router: ^14.8.1
  visibility_detector: 0.3.3
  device_info_plus: 11.2.0
  package_info_plus: 8.1.2
  connectivity_plus: any
  provider: ^6.0.1
  shelf: ^1.2.0
  flutter_screenutil: 5.9.3 # 屏幕尺寸适配
  pull_to_refresh: 2.0.0 # 下拉刷新
  card_swiper: ^2.0.4
  hive: ^2.0.4
  hive_flutter: ^1.1.0
  encrypt: ^5.0.1
  crypto: ^3.0.1
  bot_toast: ^4.0.1
  shared_preferences: ^2.0.8
  country_pickers: ^3.0.1
  hex: ^0.2.0
  easy_debounce: ^2.0.1
  qr_flutter: 4.0.0
  url_launcher: 6.1.10
  permission_handler: 10.2.0
  app_installer: ^1.1.0
  universal_html: ^2.0.8
  heif_converter_plus: ^1.0.2
  fluttertoast: 8.2.12
  image_gallery_saver_plus: ^3.0.5
  pedantic: ^1.0.0
  shelf_static: ^1.1.0
  flutter_native_splash: ^2.1.6
  url_strategy: ^0.2.0
  preload_page_view: ^0.1.6
  flutter_slidable: 3.1.2
  waterfall_flow: ^3.0.2
  flutter_emoji: ^2.4.0
  flutter_pickers: ^2.1.8
  path_provider: ^2.0.9
  marquee: any
  web_socket_channel: ^2.2.0
  drift: ^2.4.2
  sqlite3_flutter_libs: ^0.5.27
  path: ^1.8.0
  video_compress: 3.1.3
  file_picker: 8.1.7
  lottie: ^2.3.2
  lpinyin: ^2.0.3
  intl: ^0.17.0
  dotted_border: 2.0.0+1
  table_calendar: 3.0.7
  extended_text_field: ^10.2.0
  extended_text: ^9.1.2
  flutter_countdown_timer: ^4.1.0
  # extended_nested_scroll_view: 5.1.3
  extended_nested_scroll_view: ^6.0.0

  video_player:
    path: plugins/video_player
  flick_video_player:
    path: plugins/flick_video_player-0.5.0
  image_compression_flutter:
    path: plugins/image_compression_flutter-1.0.4
  flutter_html:
    path: plugins/flutter_html-3.0.0-alpha.6

  pull_to_refresh_notification: 3.1.0
  # appinio_video_player: ^1.2.0
  easy_image_viewer: ^1.2.0
  camera: ^0.10.3+2
  http_parser: ^4.0.2
  image_watermark: ^0.1.0
  worker_manager: ^4.4.6
  isolated_worker: ^0.1.1
  photo_view: ^0.14.0
  flutter_local_notifications: ^18.0.1
  flutter_ringtone_player: ^4.0.0+3
  pointer_interceptor: ^0.10.0
  common_utils: ^2.1.0
  csslib: 0.17.2
  extended_tabs: 4.2.0
  webviewx_plus: ^0.5.0
  android_id: ^0.3.6
  webcrypto: ^0.5.7

dependency_overrides:
  fading_edge_scrollview: ^4.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.0
  build_runner: ^2.3.3
  drift_dev: ^2.4.1

  # dependency_overrides:
  # video_player_android:
  #   git:
  #     url: git@172.105.200.120:rn/video_player_android-2.3.9.git
  #     ref: add_cache

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  # cupertino_icons: ^1.0.2

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  # flutter_lints: ^1.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/lottie/pull_refresh/
    - assets/lottie/pull_refresh/images/
    - assets/images/pwa/
    - assets/images/
    - assets/images/card/
    - assets/images/cg_320/
    - assets/images/common/
    - assets/images/detail/
    - assets/images/elegantroom/
    - assets/images/games/
    - assets/images/home/
    - assets/images/login/
    - assets/images/member/
    - assets/images/msg/
    - assets/images/mine/
    - assets/images/mine/v5/
    - assets/images/mymony/
    - assets/images/nav/
    - assets/images/nigotwallet/
    - assets/images/pintuan/
    - assets/images/pment/
    - assets/images/popularize/
    - assets/images/publish/
    - assets/images/pwa/
    - assets/images/share/
    - assets/images/sign/
    - assets/images/tea/
    - assets/images/tzyh/
    - assets/images/v8/
    - assets/images/welcome/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
